apiVersion: v1
kind: Service
metadata:
  namespace: public-api
  name: nlp-api
  labels:
    app: nlp-api
spec:
  selector:
    app: nlp-api
  ports:
    - port: 12377
      targetPort: 12377

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: public-api
  name: nlp-api
  labels:
    app: nlp-api
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nlp-api
  template:
    metadata:
      labels:
        app: nlp-api
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: nlp-api
          image: __IMAGE_FULL_NAME__
          imagePullPolicy: Always
          env:
          - name: APP_SENTRYDSN
            value: __SENTRY_DSN__
          - name: APP_GRPC_PORT
            value: "12377"
          ports:
            - containerPort: 12377
              protocol: TCP
