# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nlp.proto',
  package='nlp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tnlp.proto\x12\x03nlp\"\x99\x01\n\x0eKeywordRequest\x12.\n\x06method\x18\x01 \x01(\x0e\x32\x1e.nlp.KeywordRequest.MethodType\x12\x10\n\x08sentence\x18\x02 \x01(\t\x12\x0c\n\x04topK\x18\x03 \x01(\x03\x12\x10\n\x08\x61llowPOS\x18\x04 \x03(\t\"%\n\nMethodType\x12\t\n\x05TFIDF\x10\x00\x12\x0c\n\x08TextRank\x10\x01\"w\n\x0fKeywordResponse\x12.\n\x08keywords\x18\x01 \x03(\x0b\x32\x1c.nlp.KeywordResponse.Keyword\x1a\x34\n\x07Keyword\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x01\x12\x0b\n\x03pos\x18\x03 \x01(\t2\x87\x01\n\x03NLP\x12;\n\x0eKeywordExtract\x12\x13.nlp.KeywordRequest\x1a\x14.nlp.KeywordResponse\x12\x43\n\x14KeywordExtractStream\x12\x13.nlp.KeywordRequest\x1a\x14.nlp.KeywordResponse(\x01\x62\x06proto3'
)



_KEYWORDREQUEST_METHODTYPE = _descriptor.EnumDescriptor(
  name='MethodType',
  full_name='nlp.KeywordRequest.MethodType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TFIDF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TextRank', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=172,
)
_sym_db.RegisterEnumDescriptor(_KEYWORDREQUEST_METHODTYPE)


_KEYWORDREQUEST = _descriptor.Descriptor(
  name='KeywordRequest',
  full_name='nlp.KeywordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='nlp.KeywordRequest.method', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentence', full_name='nlp.KeywordRequest.sentence', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topK', full_name='nlp.KeywordRequest.topK', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allowPOS', full_name='nlp.KeywordRequest.allowPOS', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEYWORDREQUEST_METHODTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=172,
)


_KEYWORDRESPONSE_KEYWORD = _descriptor.Descriptor(
  name='Keyword',
  full_name='nlp.KeywordResponse.Keyword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='nlp.KeywordResponse.Keyword.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='nlp.KeywordResponse.Keyword.weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='nlp.KeywordResponse.Keyword.pos', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=293,
)

_KEYWORDRESPONSE = _descriptor.Descriptor(
  name='KeywordResponse',
  full_name='nlp.KeywordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='nlp.KeywordResponse.keywords', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_KEYWORDRESPONSE_KEYWORD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=293,
)

_KEYWORDREQUEST.fields_by_name['method'].enum_type = _KEYWORDREQUEST_METHODTYPE
_KEYWORDREQUEST_METHODTYPE.containing_type = _KEYWORDREQUEST
_KEYWORDRESPONSE_KEYWORD.containing_type = _KEYWORDRESPONSE
_KEYWORDRESPONSE.fields_by_name['keywords'].message_type = _KEYWORDRESPONSE_KEYWORD
DESCRIPTOR.message_types_by_name['KeywordRequest'] = _KEYWORDREQUEST
DESCRIPTOR.message_types_by_name['KeywordResponse'] = _KEYWORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeywordRequest = _reflection.GeneratedProtocolMessageType('KeywordRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDREQUEST,
  '__module__' : 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:nlp.KeywordRequest)
  })
_sym_db.RegisterMessage(KeywordRequest)

KeywordResponse = _reflection.GeneratedProtocolMessageType('KeywordResponse', (_message.Message,), {

  'Keyword' : _reflection.GeneratedProtocolMessageType('Keyword', (_message.Message,), {
    'DESCRIPTOR' : _KEYWORDRESPONSE_KEYWORD,
    '__module__' : 'nlp_pb2'
    # @@protoc_insertion_point(class_scope:nlp.KeywordResponse.Keyword)
    })
  ,
  'DESCRIPTOR' : _KEYWORDRESPONSE,
  '__module__' : 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:nlp.KeywordResponse)
  })
_sym_db.RegisterMessage(KeywordResponse)
_sym_db.RegisterMessage(KeywordResponse.Keyword)



_NLP = _descriptor.ServiceDescriptor(
  name='NLP',
  full_name='nlp.NLP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=296,
  serialized_end=431,
  methods=[
  _descriptor.MethodDescriptor(
    name='KeywordExtract',
    full_name='nlp.NLP.KeywordExtract',
    index=0,
    containing_service=None,
    input_type=_KEYWORDREQUEST,
    output_type=_KEYWORDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='KeywordExtractStream',
    full_name='nlp.NLP.KeywordExtractStream',
    index=1,
    containing_service=None,
    input_type=_KEYWORDREQUEST,
    output_type=_KEYWORDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NLP)

DESCRIPTOR.services_by_name['NLP'] = _NLP

# @@protoc_insertion_point(module_scope)
